#version 450
#extension GL_EXT_scalar_block_layout : enable
layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2 ) in;
#define complex64_t vec2
#define float_atomic_t uint

#ifdef VULKAN
#define atomicAddFloatX(MEM, INDATA)      \
{                                         \
    uint expected_mem = MEM;              \
    uint new_mem = floatBitsToUint(uintBitsToFloat(MEM) + INDATA); \
    uint returned_mem = atomicCompSwap(MEM, expected_mem, new_mem); \
    while(returned_mem != expected_mem){ \
         expected_mem = returned_mem; \
         new_mem = floatBitsToUint(uintBitsToFloat(expected_mem) + INDATA); \
         returned_mem = atomicCompSwap(MEM, expected_mem, new_mem); \
    } \
}
#endif

layout(std430, binding = 0) uniform initData{
    
	int Nl;
	int Nt;
	int Nf;
	
	float t_min;
	float dt;
	float w_min;

} init_d;

layout(std430, binding = 1) uniform iterData{
    
    float a;
	int Nw;
	float dxw;

} iter_d;

//layout(std430, binding = 3) readonly buffer SSBO1 {
layout(std430, binding = 3) buffer SSBO1 {
   float_atomic_t S_kl_FT_d[];
};

// layout(std430, binding = 4) writeonly buffer SSBO2 {
   // complex64_t spectrum_FT_d[];
// };


void main() {
    const float pi = 3.141592653589793f;

	//uint k = gl_GlobalInvocationID.x;
	uint k = gl_LocalInvocationID.x + gl_WorkGroupSize.x * gl_WorkGroupID.x;
	uint l = gl_WorkGroupID.y;

	if (k >= init_d.Nf) return;
	//if (l >= iter_d.Nw) return;

	float w_l = 0.0;
    float mul = 0.0;
    complex64_t res = complex64_t(0.0, 0.0);
    float resR, resI;
	
	
	float x = k / (2.0 * init_d.Nf * init_d.dt);
	
	int sk = 2;
	int sl = 2*init_d.Nf;

    //for (int l=0; l < iter_d.Nw; l++){
	w_l = (1.0 + iter_d.a) * init_d.w_min * exp(l*iter_d.dxw);
	mul = exp(-pi * x * w_l) / init_d.dt;
	resR = S_kl_FT_d[l*sl + k*sk] * mul;
	resI = S_kl_FT_d[l*sl + k*sk + 1] * mul;
    
	//spectrum_FT_d[k] = res;
	//S_kl_FT_d[k] = res;
	atomicAddFloatX(S_kl_FT_d[2*k],   resR);
	atomicAddFloatX(S_kl_FT_d[2*k+1], resI);
}
